main:
  web_trigger_update: &web_trigger_update
    - name: Update Docker images
      services:
        - docker
      stages:
        - name: download models
          script: |
            mkdir -p models-enzh/enzh
            base_url="https://github.com/mozilla/firefox-translations-models/raw/refs/heads/main/models/base/enzh"
            files=(
              "lex.50.50.enzh.s2t.bin.gz"
              "model.enzh.intgemm.alphas.bin.gz"
              "srcvocab.enzh.spm.gz"
              "trgvocab.enzh.spm.gz"
            )
            for file in "${files[@]}"; do
              echo "Downloading $file"
              curl -sL "$base_url/$file" -o "models-enzh/enzh/$file"
              gunzip -f "models-enzh/enzh/$file"
              extracted_file="${file%.gz}"
              echo "$extracted_file downloaded and extracted"
            done
            echo "Download completed. Model structure:"
            pwd
            ls -R models-enzh
        - name: docker login
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: docker build
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest -f Dockerfile.enzh .
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
